### PR TITLE
Adding Styling to Leaderboard App

### PR DESCRIPTION
**Pull request by Carshy**
In this project, I added styling effects to make the app look great. Some of the CSS style effects added include hover effects, box shadows, and colors.

### CODE REVIEW

**Review by Bondok6 — COMMENTED** [review]
## Hi @Carshy 🙋‍♂️, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have JavaScript Linter `Eslint`, kindly add it 👌
- You should use [html&css + javascript](https://github.com/microverseinc/linters-config/blob/master/html-css-js) Linter for projects that require you to use both JavaScript and HTML & CSS

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Carshy** [comment]
I added Eslint as requested and all checks are successful. @Bondok6 thank you for your review it was really helpful

**Review by Nemwel-Boniface — CHANGES_REQUESTED** [review]
## Hello @Carshy           :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

You have done a great job in reaching to this milestone :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] For some reason, I am unable to start the webpack server and I have not been able to view your project live on my local machine. I have tried to reach out to you via slack but you seem  to not be responsive. Kindly fix this.

**These are some of the errors I am getting when I try to npm install:**

image


**This is what I get when I try to start the server**

image

**Note** if the project runs correctly on your local machine kindly include screenshots of the live version in a comment and request for a re-review the next reviewer should approve it. If not, kindly see why your server is not starting by checking your webpack configuration.

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Carshy** [comment]
Hello, as requested, the project is running well in my local machine. Webpack is well set and responding appropriately. @Bondok6 there are no challenges app is responding well in my local machine. Here are the screen shots as requested:

npm start1
npm start

**Review by sumairq — APPROVED** [review]
### Hi @Carshy  , 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
